### ISSUE TITLE
The ebean-maven-plugin is not recognized to be threadSafe by Maven

### ISSUE THREAD

**Issue by focbenz** [ebean-orm-tools/ebean-maven-plugin#20]
The ebean-maven-plugin is not recognized to be threadSafe by Maven and the following warning is printed if Maven finds versions <= 13.6.2

```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in FOCONIS ZAK-Root:
[WARNING] io.ebean:ebean-maven-plugin:13.5.0
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************
```

As @rPraml stated [here](https://github.com/ebean-orm/ebean/pull/2332#issuecomment-910050956) the plugin should be thread-safe and could be marked @threadSafe

**Comment by rPraml** [comment]
Thanks @focbenz for this PR.
I checked the https://stackoverflow.com/questions/22133520/maven-thread-safe-plugin-pitfalls and see no problems in this change:
- instantiation strategy is `per-lookup`
- no static member variables
- each invocation writes in own folder (target/classes, target/test-classes for each project)

@rbygrave With parallelism, we could also increase the ebean build speed. As we now have ~50 maven modules, some can be built parallel. I get these numbers on my machine
- `mvn clean install` 02:53 min
- `mvn clean install -T 8` 02:02 min
- `mvn clean install -DskipTests` 01:41 min
- `mvn clean install -DskipTests -T 8`  01:17 min
